# Site
name: 'SDSU COMP TOX'
description: 'things'
# logo: 'assets/images/logo.png'
# favicon: 'assets/images/favicon.ico'
# baseurl: "/"
# baseurl: ""
email: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
# Team names, titles and social links
people:
- name: Uduak George
  pic: missing
  position: PI
  email: ugeorge@sdsu.edu

- name: Karilyn Sant
  pic: missing
  position: PI
  email: ksant@sdsu.edu

- name: Ashley Schwartz
  pic: missing
  position: Graduate Student
  email: avschwartz@sdsu.edu


 
# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]