# Site
name: 'SDSU COMP TOX'
description: 'things'
# logo: 'assets/images/logo.png'
# favicon: 'assets/images/favicon.ico'
# baseurl: "/"
# baseurl: ""
email: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
# Team names, titles and social links
people:
- name: Uduak George
  pic: Uduak
  position: Principal Investigator
  email: ugeorge@sdsu.edu
  website: https://georgelab.sdsu.edu/
  about: Dr. Uduak George is an Associate Professor of Mathematics and Statistics at San Diego State University. More information about her research can be found on her personal George Lab webpage.

- name: Karilyn Sant
  pic: Kari
  position: Principal Investigator
  email: ksant@sdsu.edu
  website: https://publichealth.sdsu.edu/people/karilyn-sant/
  about: Dr. Karilyn Sant is an Associate Professor of Environmental Health in the San Diego State University School of Public Health. More information about her research can be found on her personal webpage.

- name: Ashley Schwartz
  pic: Ashley
  position: Graduate Student
  website: https://ashleyschwartz.com/
  email: avschwartz@sdsu.edu
  about: Ashley is a computational science PhD candidate affiliated with the Computational Science Research Center at SDSU. She is jointly advised by Dr. George and Dr. Sant in computational toxicology. More information about her personal research and news can be found on her personal website. 


 
# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]